import tenisImg from '../assets/images/tenis.png';
export const cardsInfo = [
  {
    id: 1,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: true,
    url: tenisImg,
    marca: 'k-swiss',
  },
  {
    id: 2,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V5 - Feminino',
    discountPrice: '$180',
    price: '$350',
    isDiscount: false,
    url: tenisImg,
    marca: 'k-swiss',
  },
  {
    id: 3,
    discountPercentual: 30,
    category: 'Blusa',
    productName: 'K-Swiss - Masculino',
    discountPrice: '$1000',
    price: '$2000',
    isDiscount: true,
    url: tenisImg,
    marca: 'k-swiss',
  },
  {
    id: 4,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: true,
    url: tenisImg,
    marca: 'k-swiss',
  },
  {
    id: 5,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: false,
    url: tenisImg,
    marca: 'k-swiss',
  },
  {
    id: 6,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: true,
    url: tenisImg,
    marca: 'k-swiss',
  },
  {
    id: 7,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: true,
    url: tenisImg,
    marca: 'k-swiss',
  },
  {
    id: 8,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: false,
    url: tenisImg,
    marca: 'k-swiss',
  },
  {
    id: 9,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: false,
    url: tenisImg,
    marca: 'k-swiss',
  },
  {
    id: 10,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'Nike V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: false,
    url: tenisImg,
    marca: 'nike',
  },
  {
    id: 11,
    discountPercentual: 30,
    type: 'Tênis',
    productName: 'Nike V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: false,
    url: tenisImg,
    marca: 'nike',
    category: 'esporte e lazer',
    genero: 'masc',
    isNew: true,
  },
  {
    id: 12,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'Adidas V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: false,
    url: tenisImg,
    marca: 'adidas',
  },
  {
    id: 13,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'Nike V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: false,
    url: tenisImg,
    marca: 'nike',
  },
  {
    id: 14,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'Adidas V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: false,
    url: tenisImg,
    marca: 'adidas',
  },
];
