import tenisImg from '../assets/images/tenis.png';
export const cardsInfo = [
  {
    id: 1,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 2,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V5 - Feminino',
    discountPrice: '$180',
    price: '$350',
    isDiscount: false,
    url: tenisImg,
  },
  {
    id: 3,
    discountPercentual: 30,
    category: 'Blusa',
    productName: 'K-Swiss - Masculino',
    discountPrice: '$1000',
    price: '$2000',
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 4,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 5,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: false,
    url: tenisImg,
  },
  {
    id: 6,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 7,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 8,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: false,
    url: tenisImg,
  },
  {
    id: 8,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: false,
    url: tenisImg,
  },
  {
    id: 8,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: false,
    url: tenisImg,
  },
  {
    id: 8,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: false,
    url: tenisImg,
  },
  {
    id: 8,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: false,
    url: tenisImg,
  },
  {
    id: 8,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: false,
    url: tenisImg,
  },
  {
    id: 8,
    discountPercentual: 30,
    category: 'Tênis',
    productName: 'K-Swiss V8 - Masculino',
    discountPrice: '$100',
    price: '$200',
    isDiscount: false,
    url: tenisImg,
  },
];
